"use client";
import { useEffect, useState } from "react";
import { confirmPlan, createQuest, reportSession, rescueQuest, routeGoal } from "@/lib/agent";
import type { Quest, Subtask } from "@/lib/types";

type View = "today" | "quests" | "calendar" | "preview" | "detail" | "focus" | "result" | "recovery";
const boss = `      .--.  .--.
     :   \\__/   :
      \\  o  o  /
       \\   '  /
        \\ -- /
       /|    |\\`;
const smallMonster = `  .-.\n (o o)\n | O |\n  '-'`;
const fmt = (value?: string) => value ? new Intl.DateTimeFormat("zh-TW", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—";

export default function Home() {
  const [goal, setGoal] = useState(""); const [openInput, setOpenInput] = useState(false);
  const [quests, setQuests] = useState<Quest[]>([]); const [activeId, setActiveId] = useState<string | null>(null);
  const [view, setView] = useState<View>("today"); const [sessionId, setSessionId] = useState<string | null>(null);
  useEffect(() => { const raw = localStorage.getItem("quest-agent-state"); if (!raw) return; const saved = JSON.parse(raw) as Quest | Quest[]; const list = (Array.isArray(saved) ? saved : [saved]).map((q) => ({ ...q, planState: q.planState ?? "confirmed" })); setQuests(list); setActiveId(list[0]?.id ?? null); }, []);
  useEffect(() => { if (quests.length) localStorage.setItem("quest-agent-state", JSON.stringify(quests)); }, [quests]);
  const quest = quests.find((q) => q.id === activeId) ?? null;
  const update = (fn: (q: Quest) => Quest) => setQuests((list) => list.map((q) => q.id === activeId ? fn(q) : q));
  const add = () => { if (!goal.trim()) return; const q = createQuest(goal); setQuests((list) => [...list, q]); setActiveId(q.id); setOpenInput(false); setView("preview"); };
  const nextTask = (q = quest): Subtask | undefined => q?.subtasks.find((s) => ["planned", "in_progress", "partial"].includes(s.status));
  const begin = (id: string) => { update((q) => reportSession(q, id, "start")); setSessionId(id); setView("focus"); };
  const result = (outcome: "complete" | "partial" | "stuck" | "missed") => { if (!sessionId) return; if (outcome === "stuck" || outcome === "missed") { setView("recovery"); return; } update((q) => reportSession(q, sessionId, outcome)); setView("result"); };
  const activeTask = quest?.subtasks.find((s) => s.id === sessionId) ?? nextTask();
  const nav = (next: View) => setView(next);
  const isBoss = quest?.type === "complex_quest";
  return <main>
    <nav><button className="brand" onClick={() => nav("today")}>Quest Agent</button><div><button className={view === "today" ? "active" : ""} onClick={() => nav("today")}>今天</button><button className={view === "quests" || view === "detail" ? "active" : ""} onClick={() => nav("quests")}>任務</button><button className={view === "calendar" ? "active" : ""} onClick={() => nav("calendar")}>行事曆</button></div><aside><button className="new-task" onClick={() => { nav("today"); setOpenInput(true); }}>＋ 新增任務</button><span>Lv. {quest?.level ?? 3}<b>{quest?.xp ?? 0} / 600 XP</b></span></aside></nav>
    {view === "today" && <section className="page today"><header><p>早安 ☀️</p><h1>慢慢來，我們先處理下一件。</h1><span>今天有 {quests.filter((q) => q.planState === "confirmed").length} 個進行中的任務。</span></header>{openInput ? <section className="add"><textarea autoFocus value={goal} onChange={(e) => setGoal(e.target.value)} placeholder="例如：9/10 前完成統計報告，我星期三晚上沒空。"/><div><button className="secondary" onClick={() => setOpenInput(false)}>取消</button><button onClick={add}>交給 Agent →</button></div></section> : <button className="add-trigger" onClick={() => setOpenInput(true)}>＋ 告訴 Agent 你想做什麼</button>}{quest && nextTask() ? <section className="next card"><div><p className="label">下一個任務</p><h2>{quest.title}</h2><span className="pill">{isBoss ? "Boss Quest" : "小任務"} · {quest.status}</span><div className="hp"><i style={{ width: `${quest.bossHp}%` }}/></div><b>{quest.bossHp} / 100 HP</b><h3>{nextTask()!.title}</h3><p>{fmt(nextTask()!.scheduledAt)} · {nextTask()!.minutes} 分鐘 · {nextTask()!.damage} Damage</p><button onClick={() => begin(nextTask()!.id)}>開始這一關</button><button className="secondary" onClick={() => begin(nextTask()!.id)}>先做 3 分鐘</button><small>{quest.constraints[0] ?? "Agent 已保留緩衝時間，讓你不必趕工。"}</small></div><pre className="ascii-monster">{isBoss ? boss : smallMonster}</pre></section> : <section className="card empty">目前沒有已確認的工作階段。先告訴 Agent 你的目標吧。</section>}<section className="calendar-mini card"><h2>今天</h2>{(quest?.events ?? []).slice(0, 5).map((e) => <p key={e.id}><time>{fmt(e.start)}</time><b>{e.title}</b></p>)}<button className="text" onClick={() => nav("calendar")}>查看完整行事曆 →</button></section></section>}
    {view === "preview" && quest && <section className="page preview"><button className="text" onClick={() => nav("today")}>← 返回</button><div className="preview-grid"><article><p className="label">排程預覽</p><h1>{quest.title}</h1><p>截止時間：{fmt(quest.deadline)}</p><pre className="ascii-monster">{isBoss ? boss : smallMonster}</pre><h2>Agent 理解到：</h2><ul>{quest.constraints.length ? quest.constraints.map((x) => <li key={x}>{x}</li>) : <li>這個目標需要安排專注時段與緩衝。</li>}<li>{routeGoal(quest.source).reason}</li></ul><h2>任務拆解</h2>{quest.subtasks.map((s, i) => <div className="breakdown" key={s.id}><b>{i + 1}. {s.title}</b><span>{fmt(s.scheduledAt)} · {s.minutes} 分鐘 · {s.damage} DMG</span></div>)}<div className="routes"><div><b>理想完成</b><strong>{fmt(quest.safeFinish)}</strong><span>這是實際排入 Calendar 的路線。</span></div><div><b>安全備用線</b><strong>{fmt(quest.criticalDeadline)}</strong><span>延誤時 Agent 才會啟用，不會直接寫入 Calendar。</span></div></div><footer><button onClick={() => { update(confirmPlan); nav("today"); }}>確認這個排程</button><button className="secondary" onClick={() => update((q) => ({ ...q, lastSignal: "Agent 已記下：請讓這個計畫更輕鬆。" }))}>再輕鬆一點</button><button className="secondary" onClick={() => update((q) => ({ ...q, lastSignal: "Agent 已記下：請讓工作階段更集中。" }))}>再集中一點</button></footer></article><aside className="calendar-preview"><h2>排程放在哪裡？</h2>{quest.events.map((e) => <div key={e.id}><time>{fmt(e.start)}</time><b>{e.title}</b><span>{Math.round((new Date(e.end).getTime()-new Date(e.start).getTime())/60000)} 分鐘</span></div>)}</aside></div></section>}
    {view === "quests" && <section className="page"><header><p>我的任務</p><h1>進行中的 Quest</h1></header><div className="quest-list">{quests.map((q) => <button className="quest-card" key={q.id} onClick={() => { setActiveId(q.id); nav(q.planState === "preview" ? "preview" : "detail"); }}><span>{q.type === "complex_quest" ? "Boss Quest" : "小任務"}</span><h2>{q.title}</h2><div className="hp"><i style={{ width: `${q.bossHp}%` }}/></div><b>{q.bossHp}/100 HP · {q.status}</b></button>)}</div></section>}
    {view === "calendar" && <section className="page"><header><p>行事曆</p><h1>Agent 安排的工作時段</h1><span>暖橘色區塊代表 Agent Session；安全備用線不會顯示在這裡。</span></header><section className="week card">{(quest?.events ?? []).map((e) => <div key={e.id}><time>{fmt(e.start)}</time><b>{e.title}</b><span>Agent Session</span></div>)}</section></section>}
    {view === "detail" && quest && <section className="page detail"><button className="text" onClick={() => nav("quests")}>← 任務</button><section className="detail-head card"><pre className="ascii-monster">{isBoss ? boss : smallMonster}</pre><div><p className="label">{isBoss ? "Boss Quest" : "小任務"}</p><h1>{quest.title}</h1><div className="hp"><i style={{ width: `${quest.bossHp}%` }}/></div><b>{quest.bossHp} / 100 HP · {quest.status}</b><p>Deadline {fmt(quest.deadline)}　理想完成 {fmt(quest.safeFinish)}　緩衝 {quest.bufferHours} 小時</p></div></section>{nextTask() && <section className="next card"><div><p className="label">下一個工作階段</p><h2>{nextTask()!.title}</h2><p>{fmt(nextTask()!.scheduledAt)} · {nextTask()!.minutes} 分鐘 · {nextTask()!.damage} Damage</p><button onClick={() => begin(nextTask()!.id)}>開始</button></div></section>}<section className="card"><h2>後續 Session</h2>{quest.subtasks.filter((s) => s.id !== nextTask()?.id).map((s, i) => <p className="line" key={s.id}>{i + 2}. <b>{s.title}</b><span>{fmt(s.scheduledAt)} · {s.minutes} 分鐘</span></p>)}</section><section className="why card"><h2>Agent 為什麼這樣安排？</h2><p>{quest.constraints[0] ?? "我把需要專注的內容分散到不同時段，並保留緩衝。"}</p><p>如果前面的 Session 延誤，我會重新計算後面的安排。</p></section></section>}
    {view === "focus" && quest && activeTask && <section className="focus"><button className="text" onClick={() => nav("detail")}>← 返回任務</button><button className="exit" onClick={() => nav("detail")}>× 離開</button><p>{quest.title} · 第 {quest.subtasks.findIndex((s) => s.id === activeTask.id)+1}/{quest.subtasks.length} 關</p><pre className="ascii-monster">{isBoss ? boss : smallMonster}</pre><h1>{activeTask.title}</h1><strong>{activeTask.minutes}:00</strong><h2>本回合目標</h2><p>完成這一小段即可；不用把整個 Quest 一次做完。</p><h2>最低勝利條件</h2><p>先完成一個最小、可繼續的下一步。</p><button onClick={() => result("complete")}>結束並回報</button><div><button className="secondary" onClick={() => result("stuck")}>我卡住了</button><button className="secondary" onClick={() => result("partial")}>我有做一些</button></div></section>}
    {view === "result" && quest && <section className="page result"><p className="label">這一關進行得怎麼樣？</p><h1>⚔ HIT!</h1><strong>{activeTask?.damage ?? 0} DAMAGE</strong><p>Boss HP {Math.min(100, quest.bossHp + (activeTask?.damage ?? 0))} → {quest.bossHp}</p><p>+{activeTask?.damage ?? 0} XP</p><button onClick={() => nav("today")}>回到今天</button><button className="secondary" onClick={() => nav("detail")}>查看 Quest</button></section>}
    {view === "recovery" && quest && <section className="page recovery"><p className="label">救援模式</p><h1>我幫你重新算了一次。</h1><p>這一關沒有按照原計畫完成，但 Agent 會先保護你的節奏，再安排下一步。</p><section className="card"><b>緩衝時間</b><h2>{quest.bufferHours} 小時 → {Math.max(0, quest.bufferHours - 12)} 小時</h2><p>Boss 進入警戒狀態，但不會扣除永久 XP。</p></section><button onClick={() => { if (sessionId) update((q) => rescueQuest(q, sessionId, "卡住或未開始")); nav("detail"); }}>接受新的安排</button><button className="secondary" onClick={() => nav("detail")}>自己調整</button></section>}
  </main>;
}
