"use client";
import { useEffect,useMemo,useState } from "react";
import { createQuest } from "@/lib/agent";
import type { Quest } from "@/lib/types";
import { AsciiMonster } from "./components/AsciiMonster";
import { Card } from "./components/ui";
import "./today.css";import "./today-polish.css";
const t=(x?:string)=>x?new Intl.DateTimeFormat("zh-TW",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(x)):"—";
export default function Home(){const[qs,setQs]=useState<Quest[]>([]),[goal,setGoal]=useState(""),[open,setOpen]=useState(false);useEffect(()=>{const x=localStorage.getItem("quest-agent-state");if(x)setQs(Array.isArray(JSON.parse(x))?JSON.parse(x):[JSON.parse(x)])},[]);useEffect(()=>{if(qs.length)localStorage.setItem("quest-agent-state",JSON.stringify(qs))},[qs]);const items=useMemo(()=>qs.flatMap(q=>q.subtasks.filter(s=>s.status!=="complete").map(s=>({q,s}))).sort((a,b)=>+new Date(a.s.scheduledAt)-+new Date(b.s.scheduledAt)),[qs]);const today=items.filter(x=>new Date(x.s.scheduledAt).toDateString()===new Date().toDateString());const next=today[0]??items[0];const add=()=>{if(goal){setQs(x=>[...x,createQuest(goal)]);setGoal("");setOpen(false)}};return <main className="today-shell"><nav className="top-nav"><b>Quest Agent</b><div><button className="nav-active">今天</button><button>任務</button><button>行事曆</button></div><span>Lv. 3<strong>420 / 600 XP</strong></span></nav><section className="today-page"><header><p>早安 ☀️</p><h1>今天先完成眼前這一關。</h1><small>還有 {items.length} 個安排，Agent 會幫你顧著。</small></header>{next&&<Card className="next-quest compact"><div className="next-copy"><p className="eyebrow">下一關</p><h2>{next.q.title}</h2><b>{next.q.bossHp}/100 HP · {next.q.status}</b><div className="hp"><i style={{width:`${next.q.bossHp}%`}}/></div><h3>{next.s.title}</h3><p>{t(next.s.scheduledAt)} · {next.s.minutes} 分鐘</p><button>開始這一關</button><button className="soft">先做 3 分鐘</button><button className="text">重新安排</button></div><div className="monster-wrap"><AsciiMonster variant="boss"/><small>CV BOSS</small></div></Card>}<section className="add-task"><button onClick={()=>setOpen(!open)}>＋ 告訴 Agent 你想完成什麼</button>{open&&<div><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="例如：9/10 前完成統計報告，我星期三晚上沒空。"/><button onClick={add}>交給 Agent →</button></div>}</section><section className="today-grid"><Card className="calendar-grid"><p className="eyebrow">今天的行事曆</p><p className="event normal"><time>12:00</time><span><b>午餐與休息</b></span></p>{today.map(({q,s})=><p className="event agent" key={s.id}><time>{t(s.scheduledAt)}</time><span><b>{s.title}</b><small>{q.title} · {s.minutes} 分鐘</small></span></p>)}</Card><section className="quest-side">{qs.slice(0,3).map(q=><Card className="compact-quest" key={q.id}><AsciiMonster variant="boss"/><div><b>{q.title}</b><div className="hp"><i style={{width:`${q.bossHp}%`}}/></div><small>{q.bossHp}/100 HP · {q.status}</small></div></Card>)}</section></section></section></main>}
