"use client";
import { useEffect, useMemo, useState } from "react";
import { confirmPlan, createQuest, reportSession, rescueQuest } from "@/lib/agent";
import type { Quest, Subtask } from "@/lib/types";

type Screen="today"|"preview"|"sync"|"quests"|"calendar"|"detail"|"focus"|"report"|"result"|"recovery";
const BOSS=` .--.  .--.\n:   \\__/   :\n \\  o  o  /\n  \\  --  /\n /|    |\\`; const ANGRY=` .-""-.\n/ >  < \\\n|   ^   |\n\\  --  /`; const SMALL=` .-.\n(o o)\n| O |\n '-'`;
const time=(v?:string)=>v?new Intl.DateTimeFormat("zh-TW",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v)):"—";
const sameDay=(v:string)=>{const a=new Date(v),b=new Date();return a.toDateString()===b.toDateString()};
export default function Home(){const[screen,setScreen]=useState<Screen>("today"),[qs,setQs]=useState<Quest[]>([]),[id,setId]=useState<string|null>(null),[goal,setGoal]=useState(""),[adding,setAdding]=useState(false),[sid,setSid]=useState<string|null>(null),[running,setRunning]=useState(false),[exit,setExit]=useState(false),[partial,setPartial]=useState(false),[note,setNote]=useState(""),[cal,setCal]=useState<"month"|"week">("month");
useEffect(()=>{const raw=localStorage.getItem("quest-agent-state");if(raw){const a=(Array.isArray(JSON.parse(raw))?JSON.parse(raw):[JSON.parse(raw)]).map((q:Quest)=>({...q,planState:q.planState??"confirmed"}));setQs(a);setId(a[0]?.id)}},[]);useEffect(()=>{if(qs.length)localStorage.setItem("quest-agent-state",JSON.stringify(qs))},[qs]);
const q=qs.find(x=>x.id===id), upd=(f:(x:Quest)=>Quest)=>setQs(a=>a.map(x=>x.id===id?f(x):x)); const todo=useMemo(()=>qs.filter(x=>x.planState==="confirmed").flatMap(x=>x.subtasks.filter(s=>["planned","in_progress","partial"].includes(s.status)).map(s=>({q:x,s}))).sort((a,b)=>+new Date(a.s.scheduledAt)-+new Date(b.s.scheduledAt)),[qs]);const next=todo.find(x=>sameDay(x.s.scheduledAt))??todo[0];const task=q?.subtasks.find(s=>s.id===sid);
const add=()=>{if(!goal)return;const n=createQuest(goal);setQs(a=>[...a,n]);setId(n.id);setAdding(false);setScreen("preview")};const start=(x:Quest,s:Subtask)=>{setId(x.id);setSid(s.id);setRunning(false);setScreen("focus")};const finish=(o:"complete"|"partial"|"stuck"|"missed")=>{if(!sid)return;if(o==="stuck"||o==="missed"){setScreen("recovery");return}upd(x=>reportSession(x,sid,o));setScreen("result")};
return <main><nav><b>Quest Agent</b><div>{(["today","quests","calendar"] as Screen[]).map(x=><button key={x} onClick={()=>setScreen(x)}>{x==="today"?"今天":x==="quests"?"任務":"行事曆"}</button>)}</div><button onClick={()=>{setScreen("today");setAdding(true)}}>＋ 新增任務</button></nav>
{screen==="today"&&<section className="page"><p className="label">早安 ☀️</p><h1>慢慢來，我們先處理下一件。</h1>{adding&&<div className="card"><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="例如：9/10 前完成統計報告，我星期三晚上沒空。"/><button onClick={add}>交給 Agent →</button></div>}{next?<section className="card hero"><div><p className="label">下一個任務</p><h2>{next.q.title}</h2><h3>{next.s.title}</h3><p>{time(next.s.scheduledAt)} · {next.s.minutes} 分鐘</p><button onClick={()=>start(next.q,next.s)}>開始這一關</button><button className="soft" onClick={()=>start(next.q,next.s)}>先做 3 分鐘</button><small>{next.q.constraints[0]??"Agent 已保留緩衝與休息。"}</small></div><pre>{next.q.type==="complex_quest"?BOSS:SMALL}</pre></section>:<div className="card">目前沒有已確認的工作階段。</div>}<section className="card"><h2>今天的安排</h2>{todo.filter(x=>sameDay(x.s.scheduledAt)).map(x=><p key={x.s.id}>{time(x.s.scheduledAt)}　<b>{x.s.title}</b> · {x.q.title}</p>)}</section>{next&&<section className="reminder">⚔️ {next.q.title} · 下一關：{next.s.title}<button className="soft" onClick={()=>start(next.q,next.s)}>先做 3 分鐘</button></section>}</section>}
{screen==="preview"&&q&&<section className="page"><button onClick={()=>setScreen("today")}>← 返回</button><h1>排程預覽</h1><h2>{q.title}</h2><pre>{q.type==="complex_quest"?BOSS:SMALL}</pre><p>截止時間：{time(q.deadline)}</p><h3>Agent 理解到</h3><ul>{(q.constraints.length?q.constraints:["這個目標需要拆解並保留緩衝。"]).map(x=><li key={x}>{x}</li>)}</ul><h3>任務拆解</h3>{q.subtasks.map((s,i)=><p className="line" key={s.id}>{i+1}. <b>{s.title}</b><span>{time(s.scheduledAt)} · {s.minutes} 分鐘 · {s.damage} DMG</span></p>)}<div className="card">理想完成：{time(q.safeFinish)}<br/>安全備用線：{time(q.criticalDeadline)}</div><button onClick={()=>{upd(confirmPlan);setScreen("sync")}}>{q.type==="fixed_event"?"加入行事曆":"確認這個排程"}</button></section>}
{screen==="sync"&&q&&<section className="page center"><h1>✓ 排程完成！</h1><p>已建立 {q.events.length} 個工作時段，保留 {q.bufferHours} 小時緩衝。</p><p>目前使用 Demo Calendar；串接 Google 後會在這一步同步。</p><button onClick={()=>setScreen("today")}>前往今天第一關</button></section>}
{screen==="quests"&&<section className="page"><h1>進行中的 Quest</h1><div className="grid">{qs.map(x=><button className="card" key={x.id} onClick={()=>{setId(x.id);setScreen(x.planState==="preview"?"preview":"detail")}}><pre>{x.type==="complex_quest"?BOSS:SMALL}</pre><h2>{x.title}</h2><p>{x.bossHp}/100 HP · {x.status}</p></button>)}</div></section>}
{screen==="calendar"&&<section className="page"><h1>行事曆</h1><button onClick={()=>setCal("month")}>月曆</button><button className="soft" onClick={()=>setCal("week")}>週曆</button><div className={cal==="month"?"month":"week"}>{Array.from({length:cal==="month"?30:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);const es=todo.filter(x=>new Date(x.s.scheduledAt).toDateString()===d.toDateString());return <div className="day" key={i}><b>{d.getMonth()+1}/{d.getDate()}</b>{es.map(x=><span key={x.s.id}>{x.s.title}</span>)}</div>})}</div></section>}
{screen==="detail"&&q&&<section className="page"><h1>{q.title}</h1><pre>{q.status==="DANGER"?ANGRY:BOSS}</pre><p>{q.bossHp}/100 HP · {q.status} · Buffer {q.bufferHours}h</p>{q.subtasks.map(s=><p className="line" key={s.id}><b>{s.title}</b><span>{time(s.scheduledAt)} · {s.minutes} 分鐘</span>{s.id===q.subtasks.find(x=>["planned","partial","in_progress"].includes(x.status))?.id&&<button onClick={()=>start(q,s)}>開始</button>}</p>)}</section>}
{screen==="focus"&&q&&task&&<section className="focus"><button onClick={()=>setExit(true)}>× 離開</button><pre>{BOSS}</pre><h1>{task.title}</h1><strong>{running?"24:37":"準備開始"}</strong><p>最低勝利條件：完成一個可繼續的下一步即可。</p>{!running?<><button onClick={()=>{upd(x=>reportSession(x,task.id,"start"));setRunning(true)}}>開始 {task.minutes} 分鐘</button><button className="soft" onClick={()=>{upd(x=>reportSession(x,task.id,"start"));setRunning(true)}}>先做 3 分鐘</button></>:<><button className="soft" onClick={()=>setRunning(false)}>暫停</button><button className="soft" onClick={()=>setScreen("recovery")}>我卡住了</button><button className="soft" onClick={()=>setScreen("recovery")}>縮小這一關</button><button onClick={()=>setScreen("report")}>結束並回報</button></>}{exit&&<div className="modal"><h2>要離開這一回合嗎？</h2><button onClick={()=>{setExit(false);setScreen("detail")}}>暫停並離開</button><button onClick={()=>{setExit(false);setScreen("report")}}>結束並回報</button><button className="soft" onClick={()=>setExit(false)}>繼續工作</button></div>}</section>}
{screen==="report"&&<section className="page center"><h1>這一關進行得怎麼樣？</h1>{partial?<><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="你做到哪裡了？"/><button onClick={()=>finish("partial")}>送出回報</button></>:<><button onClick={()=>finish("complete")}>✅ 完成</button><button onClick={()=>setPartial(true)}>◐ 部分完成</button><button onClick={()=>finish("stuck")}>△ 有開始但卡住</button><button onClick={()=>finish("missed")}>○ 沒有開始</button></>}</section>}
{screen==="result"&&q&&<section className="page center"><h1>{q.bossHp===0?"BOSS DEFEATED":"⚔ HIT!"}</h1><pre>{q.bossHp===0?" .--.  .--.\n:   x__x   :\n \\        /\n  '------'":BOSS}</pre><h2>{task?.damage??0} DAMAGE</h2><p>+{task?.damage??0} XP</p><button onClick={()=>setScreen("today")}>回到今天</button><button className="soft" onClick={()=>setScreen("detail")}>查看 Quest</button></section>}
{screen==="recovery"&&q&&<section className="page center"><pre>{ANGRY}</pre><h1>救援計畫</h1><p>我重新檢查了剩餘任務、可用時間與 Deadline。</p><div className="card">Buffer：{q.bufferHours} hr → {Math.max(0,q.bufferHours-12)} hr<br/>Boss 進入警戒狀態</div><button onClick={()=>{if(sid)upd(x=>rescueQuest(x,sid,"卡住或未開始"));setScreen("detail")}}>接受新的安排</button><button className="soft" onClick={()=>setScreen("detail")}>自己調整</button></section>}</main>}
